//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 05:37:44 PM CET 
//


package org.zhuzhu.xml.jaxb.calexit;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name" maxOccurs="unbounded"/>
 *         &lt;element ref="{}localname" minOccurs="0"/>
 *         &lt;element ref="{}population" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}population_growth" minOccurs="0"/>
 *         &lt;element ref="{}infant_mortality" minOccurs="0"/>
 *         &lt;element ref="{}gdp_total" minOccurs="0"/>
 *         &lt;element ref="{}gdp_agri" minOccurs="0"/>
 *         &lt;element ref="{}gdp_ind" minOccurs="0"/>
 *         &lt;element ref="{}gdp_serv" minOccurs="0"/>
 *         &lt;element ref="{}inflation" minOccurs="0"/>
 *         &lt;element ref="{}unemployment" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}indep_date" minOccurs="0"/>
 *           &lt;element ref="{}dependent" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}government" minOccurs="0"/>
 *         &lt;element ref="{}encompassed" maxOccurs="unbounded"/>
 *         &lt;element ref="{}ethnicgroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}religion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}language" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}border" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}province" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}city" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="car_code" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="area" type="{}positiveDecimal" />
 *       &lt;attribute ref="{}capital"/>
 *       &lt;attribute name="memberships" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "localname",
    "population",
    "populationGrowth",
    "infantMortality",
    "gdpTotal",
    "gdpAgri",
    "gdpInd",
    "gdpServ",
    "inflation",
    "unemployment",
    "indepDate",
    "dependent",
    "government",
    "encompassed",
    "ethnicgroup",
    "religion",
    "language",
    "border",
    "province",
    "city"
})
@XmlRootElement(name = "country")
public class Country {

    @XmlElement(required = true)
    protected List<String> name;
    protected String localname;
    protected List<Population> population;
    @XmlElement(name = "population_growth")
    protected BigDecimal populationGrowth;
    @XmlElement(name = "infant_mortality")
    protected BigDecimal infantMortality;
    @XmlElement(name = "gdp_total")
    protected BigDecimal gdpTotal;
    @XmlElement(name = "gdp_agri")
    protected BigDecimal gdpAgri;
    @XmlElement(name = "gdp_ind")
    protected BigDecimal gdpInd;
    @XmlElement(name = "gdp_serv")
    protected BigDecimal gdpServ;
    protected BigDecimal inflation;
    protected BigDecimal unemployment;
    @XmlElement(name = "indep_date")
    protected IndepDate indepDate;
    protected Dependent dependent;
    protected String government;
    @XmlElement(required = true)
    protected List<Encompassed> encompassed;
    protected List<PercentageProperty> ethnicgroup;
    protected List<PercentageProperty> religion;
    protected List<PercentageProperty> language;
    protected List<Border> border;
    protected List<Province> province;
    protected List<City> city;
    @XmlAttribute(name = "car_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String carCode;
    @XmlAttribute(name = "area")
    protected BigDecimal area;
    @XmlAttribute(name = "capital")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object capital;
    @XmlAttribute(name = "memberships")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> memberships;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getName() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the localname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * Sets the value of the localname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalname(String value) {
        this.localname = value;
    }

    /**
     * Gets the value of the population property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the population property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPopulation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Population }
     * 
     * 
     */
    public List<Population> getPopulation() {
        if (population == null) {
            population = new ArrayList<Population>();
        }
        return this.population;
    }

    /**
     * Gets the value of the populationGrowth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPopulationGrowth() {
        return populationGrowth;
    }

    /**
     * Sets the value of the populationGrowth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPopulationGrowth(BigDecimal value) {
        this.populationGrowth = value;
    }

    /**
     * Gets the value of the infantMortality property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInfantMortality() {
        return infantMortality;
    }

    /**
     * Sets the value of the infantMortality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInfantMortality(BigDecimal value) {
        this.infantMortality = value;
    }

    /**
     * Gets the value of the gdpTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGdpTotal() {
        return gdpTotal;
    }

    /**
     * Sets the value of the gdpTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGdpTotal(BigDecimal value) {
        this.gdpTotal = value;
    }

    /**
     * Gets the value of the gdpAgri property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGdpAgri() {
        return gdpAgri;
    }

    /**
     * Sets the value of the gdpAgri property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGdpAgri(BigDecimal value) {
        this.gdpAgri = value;
    }

    /**
     * Gets the value of the gdpInd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGdpInd() {
        return gdpInd;
    }

    /**
     * Sets the value of the gdpInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGdpInd(BigDecimal value) {
        this.gdpInd = value;
    }

    /**
     * Gets the value of the gdpServ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGdpServ() {
        return gdpServ;
    }

    /**
     * Sets the value of the gdpServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGdpServ(BigDecimal value) {
        this.gdpServ = value;
    }

    /**
     * Gets the value of the inflation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInflation() {
        return inflation;
    }

    /**
     * Sets the value of the inflation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInflation(BigDecimal value) {
        this.inflation = value;
    }

    /**
     * Gets the value of the unemployment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnemployment() {
        return unemployment;
    }

    /**
     * Sets the value of the unemployment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnemployment(BigDecimal value) {
        this.unemployment = value;
    }

    /**
     * Gets the value of the indepDate property.
     * 
     * @return
     *     possible object is
     *     {@link IndepDate }
     *     
     */
    public IndepDate getIndepDate() {
        return indepDate;
    }

    /**
     * Sets the value of the indepDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndepDate }
     *     
     */
    public void setIndepDate(IndepDate value) {
        this.indepDate = value;
    }

    /**
     * Gets the value of the dependent property.
     * 
     * @return
     *     possible object is
     *     {@link Dependent }
     *     
     */
    public Dependent getDependent() {
        return dependent;
    }

    /**
     * Sets the value of the dependent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependent }
     *     
     */
    public void setDependent(Dependent value) {
        this.dependent = value;
    }

    /**
     * Gets the value of the government property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovernment() {
        return government;
    }

    /**
     * Sets the value of the government property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovernment(String value) {
        this.government = value;
    }

    /**
     * Gets the value of the encompassed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encompassed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncompassed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Encompassed }
     * 
     * 
     */
    public List<Encompassed> getEncompassed() {
        if (encompassed == null) {
            encompassed = new ArrayList<Encompassed>();
        }
        return this.encompassed;
    }

    /**
     * Gets the value of the ethnicgroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ethnicgroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEthnicgroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PercentageProperty }
     * 
     * 
     */
    public List<PercentageProperty> getEthnicgroup() {
        if (ethnicgroup == null) {
            ethnicgroup = new ArrayList<PercentageProperty>();
        }
        return this.ethnicgroup;
    }

    /**
     * Gets the value of the religion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the religion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReligion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PercentageProperty }
     * 
     * 
     */
    public List<PercentageProperty> getReligion() {
        if (religion == null) {
            religion = new ArrayList<PercentageProperty>();
        }
        return this.religion;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PercentageProperty }
     * 
     * 
     */
    public List<PercentageProperty> getLanguage() {
        if (language == null) {
            language = new ArrayList<PercentageProperty>();
        }
        return this.language;
    }

    /**
     * Gets the value of the border property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the border property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Border }
     * 
     * 
     */
    public List<Border> getBorder() {
        if (border == null) {
            border = new ArrayList<Border>();
        }
        return this.border;
    }

    /**
     * Gets the value of the province property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the province property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProvince().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Province }
     * 
     * 
     */
    public List<Province> getProvince() {
        if (province == null) {
            province = new ArrayList<Province>();
        }
        return this.province;
    }

    /**
     * Gets the value of the city property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the city property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link City }
     * 
     * 
     */
    public List<City> getCity() {
        if (city == null) {
            city = new ArrayList<City>();
        }
        return this.city;
    }

    /**
     * Gets the value of the carCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarCode() {
        return carCode;
    }

    /**
     * Sets the value of the carCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarCode(String value) {
        this.carCode = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setArea(BigDecimal value) {
        this.area = value;
    }

    /**
     * Gets the value of the capital property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCapital() {
        return capital;
    }

    /**
     * Sets the value of the capital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCapital(Object value) {
        this.capital = value;
    }

    /**
     * Gets the value of the memberships property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberships property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberships().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getMemberships() {
        if (memberships == null) {
            memberships = new ArrayList<Object>();
        }
        return this.memberships;
    }

}
