//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 05:37:44 PM CET 
//


package org.zhuzhu.xml.jaxb.calexit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}country" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}continent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}organization" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}sea" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}river" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}lake" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}island" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}mountain" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}desert" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}airport" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country",
    "continent",
    "organization",
    "sea",
    "river",
    "lake",
    "island",
    "mountain",
    "desert",
    "airport"
})
@XmlRootElement(name = "mondial")
public class Mondial {

    protected List<Country> country;
    protected List<Continent> continent;
    protected List<Organization> organization;
    protected List<Sea> sea;
    protected List<River> river;
    protected List<Lake> lake;
    protected List<Island> island;
    protected List<Mountain> mountain;
    protected List<Desert> desert;
    protected List<Airport> airport;

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Country }
     * 
     * 
     */
    public List<Country> getCountry() {
        if (country == null) {
            country = new ArrayList<Country>();
        }
        return this.country;
    }

    /**
     * Gets the value of the continent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the continent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContinent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Continent }
     * 
     * 
     */
    public List<Continent> getContinent() {
        if (continent == null) {
            continent = new ArrayList<Continent>();
        }
        return this.continent;
    }

    /**
     * Gets the value of the organization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Organization }
     * 
     * 
     */
    public List<Organization> getOrganization() {
        if (organization == null) {
            organization = new ArrayList<Organization>();
        }
        return this.organization;
    }

    /**
     * Gets the value of the sea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sea }
     * 
     * 
     */
    public List<Sea> getSea() {
        if (sea == null) {
            sea = new ArrayList<Sea>();
        }
        return this.sea;
    }

    /**
     * Gets the value of the river property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the river property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRiver().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link River }
     * 
     * 
     */
    public List<River> getRiver() {
        if (river == null) {
            river = new ArrayList<River>();
        }
        return this.river;
    }

    /**
     * Gets the value of the lake property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lake property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLake().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lake }
     * 
     * 
     */
    public List<Lake> getLake() {
        if (lake == null) {
            lake = new ArrayList<Lake>();
        }
        return this.lake;
    }

    /**
     * Gets the value of the island property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the island property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsland().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Island }
     * 
     * 
     */
    public List<Island> getIsland() {
        if (island == null) {
            island = new ArrayList<Island>();
        }
        return this.island;
    }

    /**
     * Gets the value of the mountain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mountain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMountain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mountain }
     * 
     * 
     */
    public List<Mountain> getMountain() {
        if (mountain == null) {
            mountain = new ArrayList<Mountain>();
        }
        return this.mountain;
    }

    /**
     * Gets the value of the desert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the desert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDesert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Desert }
     * 
     * 
     */
    public List<Desert> getDesert() {
        if (desert == null) {
            desert = new ArrayList<Desert>();
        }
        return this.desert;
    }

    /**
     * Gets the value of the airport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Airport }
     * 
     * 
     */
    public List<Airport> getAirport() {
        if (airport == null) {
            airport = new ArrayList<Airport>();
        }
        return this.airport;
    }

}
