//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 05:37:44 PM CET 
//


package org.zhuzhu.xml.jaxb.calexit;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.zhuzhu.xml.jaxb.calexit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mountains_QNAME = new QName("", "mountains");
    private final static QName _Localname_QNAME = new QName("", "localname");
    private final static QName _Latitude_QNAME = new QName("", "latitude");
    private final static QName _Language_QNAME = new QName("", "language");
    private final static QName _Inflation_QNAME = new QName("", "inflation");
    private final static QName _GdpInd_QNAME = new QName("", "gdp_ind");
    private final static QName _GdpTotal_QNAME = new QName("", "gdp_total");
    private final static QName _Government_QNAME = new QName("", "government");
    private final static QName _GmtOffset_QNAME = new QName("", "gmtOffset");
    private final static QName _Ethnicgroup_QNAME = new QName("", "ethnicgroup");
    private final static QName _Longitude_QNAME = new QName("", "longitude");
    private final static QName _Area_QNAME = new QName("", "area");
    private final static QName _Elevation_QNAME = new QName("", "elevation");
    private final static QName _Established_QNAME = new QName("", "established");
    private final static QName _GdpAgri_QNAME = new QName("", "gdp_agri");
    private final static QName _PopulationGrowth_QNAME = new QName("", "population_growth");
    private final static QName _Length_QNAME = new QName("", "length");
    private final static QName _Religion_QNAME = new QName("", "religion");
    private final static QName _Depth_QNAME = new QName("", "depth");
    private final static QName _GdpServ_QNAME = new QName("", "gdp_serv");
    private final static QName _Islands_QNAME = new QName("", "islands");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _InfantMortality_QNAME = new QName("", "infant_mortality");
    private final static QName _Unemployment_QNAME = new QName("", "unemployment");
    private final static QName _Abbrev_QNAME = new QName("", "abbrev");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.zhuzhu.xml.jaxb.calexit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Through }
     * 
     */
    public Through createThrough() {
        return new Through();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Population }
     * 
     */
    public Population createPopulation() {
        return new Population();
    }

    /**
     * Create an instance of {@link IndepDate }
     * 
     */
    public IndepDate createIndepDate() {
        return new IndepDate();
    }

    /**
     * Create an instance of {@link Dependent }
     * 
     */
    public Dependent createDependent() {
        return new Dependent();
    }

    /**
     * Create an instance of {@link Encompassed }
     * 
     */
    public Encompassed createEncompassed() {
        return new Encompassed();
    }

    /**
     * Create an instance of {@link PercentageProperty }
     * 
     */
    public PercentageProperty createPercentageProperty() {
        return new PercentageProperty();
    }

    /**
     * Create an instance of {@link Border }
     * 
     */
    public Border createBorder() {
        return new Border();
    }

    /**
     * Create an instance of {@link Province }
     * 
     */
    public Province createProvince() {
        return new Province();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link LocatedAt }
     * 
     */
    public LocatedAt createLocatedAt() {
        return new LocatedAt();
    }

    /**
     * Create an instance of {@link LocatedOn }
     * 
     */
    public LocatedOn createLocatedOn() {
        return new LocatedOn();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Located }
     * 
     */
    public Located createLocated() {
        return new Located();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link Mountain }
     * 
     */
    public Mountain createMountain() {
        return new Mountain();
    }

    /**
     * Create an instance of {@link Members }
     * 
     */
    public Members createMembers() {
        return new Members();
    }

    /**
     * Create an instance of {@link Island }
     * 
     */
    public Island createIsland() {
        return new Island();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Lake }
     * 
     */
    public Lake createLake() {
        return new Lake();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link Continent }
     * 
     */
    public Continent createContinent() {
        return new Continent();
    }

    /**
     * Create an instance of {@link Sea }
     * 
     */
    public Sea createSea() {
        return new Sea();
    }

    /**
     * Create an instance of {@link Mondial }
     * 
     */
    public Mondial createMondial() {
        return new Mondial();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link River }
     * 
     */
    public River createRiver() {
        return new River();
    }

    /**
     * Create an instance of {@link Estuary }
     * 
     */
    public Estuary createEstuary() {
        return new Estuary();
    }

    /**
     * Create an instance of {@link Desert }
     * 
     */
    public Desert createDesert() {
        return new Desert();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mountains")
    public JAXBElement<String> createMountains(String value) {
        return new JAXBElement<String>(_Mountains_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "localname")
    public JAXBElement<String> createLocalname(String value) {
        return new JAXBElement<String>(_Localname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "latitude")
    public JAXBElement<BigDecimal> createLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Latitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PercentageProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language")
    public JAXBElement<PercentageProperty> createLanguage(PercentageProperty value) {
        return new JAXBElement<PercentageProperty>(_Language_QNAME, PercentageProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inflation")
    public JAXBElement<BigDecimal> createInflation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Inflation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gdp_ind")
    public JAXBElement<BigDecimal> createGdpInd(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GdpInd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gdp_total")
    public JAXBElement<BigDecimal> createGdpTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GdpTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "government")
    public JAXBElement<String> createGovernment(String value) {
        return new JAXBElement<String>(_Government_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gmtOffset")
    public JAXBElement<BigDecimal> createGmtOffset(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GmtOffset_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PercentageProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ethnicgroup")
    public JAXBElement<PercentageProperty> createEthnicgroup(PercentageProperty value) {
        return new JAXBElement<PercentageProperty>(_Ethnicgroup_QNAME, PercentageProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longitude")
    public JAXBElement<BigDecimal> createLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Longitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "area")
    public JAXBElement<BigDecimal> createArea(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Area_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elevation")
    public JAXBElement<BigDecimal> createElevation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Elevation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "established")
    public JAXBElement<XMLGregorianCalendar> createEstablished(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Established_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gdp_agri")
    public JAXBElement<BigDecimal> createGdpAgri(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GdpAgri_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "population_growth")
    public JAXBElement<BigDecimal> createPopulationGrowth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PopulationGrowth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "length")
    public JAXBElement<BigDecimal> createLength(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Length_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PercentageProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "religion")
    public JAXBElement<PercentageProperty> createReligion(PercentageProperty value) {
        return new JAXBElement<PercentageProperty>(_Religion_QNAME, PercentageProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "depth")
    public JAXBElement<BigDecimal> createDepth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Depth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gdp_serv")
    public JAXBElement<BigDecimal> createGdpServ(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GdpServ_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "islands")
    public JAXBElement<String> createIslands(String value) {
        return new JAXBElement<String>(_Islands_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "infant_mortality")
    public JAXBElement<BigDecimal> createInfantMortality(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_InfantMortality_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unemployment")
    public JAXBElement<BigDecimal> createUnemployment(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Unemployment_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "abbrev")
    public JAXBElement<String> createAbbrev(String value) {
        return new JAXBElement<String>(_Abbrev_QNAME, String.class, null, value);
    }

}
