//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 05:37:44 PM CET 
//


package org.zhuzhu.xml.jaxb.calexit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}watertype use="required""/>
 *       &lt;attribute name="water" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "to")
public class To {

    @XmlAttribute(name = "watertype", required = true)
    protected String watertype;
    @XmlAttribute(name = "water", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object water;

    /**
     * Gets the value of the watertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWatertype() {
        return watertype;
    }

    /**
     * Sets the value of the watertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWatertype(String value) {
        this.watertype = value;
    }

    /**
     * Gets the value of the water property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWater(Object value) {
        this.water = value;
    }

}
