//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 10:38:30 PM CET 
//


package org.zhuzhu.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.zhuzhu.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.zhuzhu.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TerminCalendar }
     * 
     */
    public TerminCalendar createTerminCalendar() {
        return new TerminCalendar();
    }

    /**
     * Create an instance of {@link TerminCalendar.Schedule }
     * 
     */
    public TerminCalendar.Schedule createTerminCalendarSchedule() {
        return new TerminCalendar.Schedule();
    }

    /**
     * Create an instance of {@link TerminCalendar.Schedule.Year }
     * 
     */
    public TerminCalendar.Schedule.Year createTerminCalendarScheduleYear() {
        return new TerminCalendar.Schedule.Year();
    }

    /**
     * Create an instance of {@link TerminCalendar.Schedule.Year.Month }
     * 
     */
    public TerminCalendar.Schedule.Year.Month createTerminCalendarScheduleYearMonth() {
        return new TerminCalendar.Schedule.Year.Month();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link TerminCalendar.Schedule.Year.Month.Day }
     * 
     */
    public TerminCalendar.Schedule.Year.Month.Day createTerminCalendarScheduleYearMonthDay() {
        return new TerminCalendar.Schedule.Year.Month.Day();
    }

}
